name: PR-Reviewer

on:
  push:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone repo
        run: |
          git clone https://github.com/Lightning-AI/lit-llama
          cd lit-llama

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          
      - name: Run Lit-Llama
        run: |
          python generate.py --prompt "Hello, my name is"

      #- name: Loop through files
       # run: |
        #  for file in src/files/*; do
         #   comment=$(python src/generate_comment.py "$file")
          #  echo "$comment" >> pr_comment.txt
          #done

    #  - name: Add PR comment
     #   uses: mshick/add-pr-comment@v2
      #  with:
       #   message-path: pr_comment.txt
        #  repo-directory: './'
         # requirements-path: 'requirements.txt'
